### ISSUE TITLE
Ready for release

### ISSUE THREAD

**Issue by Dimtar** [linuxserver/docker-rutorrent#1]
I feel this is ready for release, the normal functions work correctly. In saying that I believe the default mappings for unRaid need to be updated.

Probably:
80:8089
45566:45566

Port 80 on the docker being for the web port but using 8089 for actual communication as well as 45566 for port forwarding reasons.

**Comment by zaggash** [comment]
Hello,

You mean change the 80 port to 8089 ?
What is the 45566 port ?

**Comment by Dimtar** [comment]
I mean change the host port to 8089 so its not using the default web port.
45566 is the torrent port, most torrent programs have a port they use for
communication, commonly the port you forward on a home router. rTorrents is
45566

## 

Thanks,
Daniel

**Comment by zaggash** [comment]
I agree.
I checked the repo and it seems fine.

**Comment by sparklyballs** [comment]
not an issue, just a misunderstanding of how unraid templates and port changing works.
