### ISSUE TITLE
Peer flags are not displayed

### ISSUE THREAD

**Issue by the-lazy-fox** [linuxserver/docker-rutorrent#103]
Hi there,
I have a problem with the Country flags not display in the peers tab of my torrents.
Instead there is some "E", "IE", ...
Any idea why?

I'm using the lastest image with no specific customization.

Thanks for your help

**Comment by ghost** [comment]
Is this a dupe of #89?

**Comment by the-lazy-fox** [comment]
It seems that he did see the column at all. On my side the column is here but without flags.

**Comment by Ekynox** [comment]
I had the same problem with the two rutorrent plugins "_geoip_" and "_geoip2_".

In my case, I traced the issue to be a missing php module called "_ctype_" which is required by these plugins.

**The fix** that worked for me is to install the "**php7-ctype**" package.
This can be done by adding the command "**apk add php7-ctype**" in the **[Dockerfile](https://github.com/linuxserver/docker-rutorrent/blob/master/Dockerfile)** file and rebuild the image.

**Comment by alxlaxv** [comment]
Still KO for me...

**Comment by the-lazy-fox** [comment]
Is there any image update planned for that?

**Comment by alex-phillips** [comment]
I will test today and add it in if it fixes the issue.

**Comment by the-lazy-fox** [comment]
Hello @alex-phillips 
Any updates on this?

**Comment by the-lazy-fox** [comment]
I still have the issue after the recent update of the container

**Comment by sun1ight** [comment]
same issue
In logs:
 NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'geoip.so' (tried: /usr/lib/php7/modules/geoip.so (Error loading shared library /usr/lib/php7/modules/geoip.so: No such file or directory), /usr/lib/php7/modules/geoip.so.so (Error loading shared library /usr/lib/php7/modules/geoip.so.so: No such file or directory)) in Unknown on line 0

**Comment by RomLecat** [comment]
Same here, the issue is still happening.

**Comment by triqster1** [comment]
2 years later and this is still not fixed (among so many other issues that they flat out ignore). It's obvious these "maintainers" don't give a fuck about this image. Better use a different one.
