### ISSUE TITLE
Can't download 2+ .torrent files from the webui

### ISSUE THREAD

**Issue by the-lazy-fox** [linuxserver/docker-rutorrent#104]
Hi there,
I have a problem with the "Get .torrent" feature when I have selected 2+ items.
The following message is displayed "PHP Module zip is not installed"
Seems that zip is part of Dockerfile but seems to not be used

Any idea why?

I'm using the lastest image with no specific customization.

Thanks for your help

**Comment by alex-phillips** [comment]
It looks like the PHP zip module isn't installed. I'll get a PR to add this in.

**Comment by alex-phillips** [comment]
Fixed with PR https://github.com/linuxserver/docker-rutorrent/pull/105
