### ISSUE TITLE
CPU usage 100% rtorrent

### ISSUE THREAD

**Issue by R1skNt** [linuxserver/docker-rutorrent#108]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

synology box Intel Atom C2538 - 8 GB ram
torrent sessions: 400 torrents

rtorrent process having 100% usage on a thread all the time with just seeding of max 50 KB/s.
I just used the image yesterday it was fine at first but i do not know exactly when the problem actually started, i did basic auth on the default config just 2 lines of restriction.

i've been doing research and it seems it's related to this [https://github.com/rakshasa/rtorrent/issues/501](url)

**Comment by R1skNt** [comment]
I've been doing tests. I'm not sure what is the root cause, however, the problem occurs only if you restart the container without stopping the torrents (either on rtorrent or rutorrent) or if rtorrent crashed.
so, whenever this happens, just stop seeding the torrents then restart the container finally resume your torrents.

if it helps, I only use private trackers (no https), the same torrent sessions with same version of rtorrent works perfectly on ubuntu setup (whether on container or VM).

**Comment by R1skNt** [comment]
Almost all torrents says (tracker: time out) when the problem occurs

**Comment by laduke** [comment]
https://github.com/rakshasa/rtorrent/issues/580

root@13c73836d9ac:/# curl --version
curl 7.64.0 (x86_64-alpine-linux-musl) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libssh2/1.8.2 nghttp2/1.35.1

**Comment by R1skNt** [comment]
@laduke can i recompile for this alpine based container?

**Comment by laduke** [comment]
I dunno how. Maybe you could docker pull an older version of this image for now?

**Comment by banana-app** [comment]
It looks like this is indeed problem with regression in libcurl 7.64.0. As a interim solution:

1. login to Your container (as root) docker exec -it YOURDOCKERNAME /bin/bash
2. #echo http://dl-cdn.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
3. #apk update
4. #apk add libcurl=7.64.1-r0
5. (this is not strictly required, just for consistency): apk add curl=7.64.1-r0
6. Verify Your installation: 
#curl --version
curl 7.64.1 (x86_64-alpine-linux-musl) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libssh2/1.8.2 nghttp2/1.35.1
7. You should see libcurl/**7.64.1** 
exit and restart your container.

Enjoy! :)

**Comment by thelamer** [comment]
@banana-app Is this issue still present in the latest image?

**Comment by laduke** [comment]
seems OK
curl is version 7.65.1
