### ISSUE TITLE
Feature Request: add external ip to rtorrent.rc on container start

### ISSUE THREAD

**Issue by vasyl83** [linuxserver/docker-rutorrent#111]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Would it be possible to append the external ip into rtorrent.rc on the container start?
rtorrent.rc should contain `ip = xxx.xxx.xxx.xxx` that option is required by some private trackers in order for torrents to start.

you can easily get external ip with curl ifconfig.me/ip.

**Comment by vasyl83** [comment]
I found some help on rtorrent wiki

[setting-the-local-ip](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#setting-the-local-ip)

it should be possible to do it in the rtorrent.rc directly with that. just need to add it to default rtorrent.rc .. oh and it requiers for dnsutils to be installed in the container

**Comment by laduke** [comment]
I think you can edit the rtorrent.rc from the host? before you start the docker
curl is in the image so you could use curl ifconfig.me/ip like you say instead of dig

**Comment by vasyl83** [comment]
You are right I can do just that. I would still suggest that you add those lines as default install because many private trackers require the external ip.

**Comment by yitzhaq** [comment]
Here's what I use in my rtorrent.rc:

```
method.insert = get_public_ip_address_icanhazip, simple|private, "execute.capture=bash,-c,\"eval echo -n \$(curl -4s icanhazip.com)\""
schedule2 = ip_tick, 0, 1800, "network.local_address.set=(get_public_ip_address_icanhazip)"
```
Works fine, and no dependency on DiG nor Google.

**Comment by thelamer** [comment]
As this can be set in the config file and rutorrent configuration heavily revolves around setting up your custom config file I will be closing this.
