### ISSUE TITLE
[HELP] HTTP `502` when exposing rutorrent via linuxserver/letsencrypt container

### ISSUE THREAD

**Issue by crsantos** [linuxserver/docker-rutorrent#114]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

I've been using some docker images and they're great, they just work out of the box! 👏 

## TL;DR

I'm trying to expose this **rutorrent** via the _nginx_ of [linuxserver/letsencrypt](https://github.com/linuxserver/docker-letsencrypt) and I'm always getting a `502`.

Something like this (please don't laugh 😂):

`rutorrent` `->` `nginx-linuxserver/rutorrent`:`80` `->` `docker-compose` `<=>` `80:8080` `<=>` `nginx-linuxserver/letsencrypt` `<-` subdomain `proxy-confs` `->` `rutorrent.*`

## What

**This is not an issue, this is an attempt of asking for help**, trying to figure out if what I want to do is possible, and maybe I'm doing something wrong here. 🤔 

Be aware that I'm a _rookie_ docker/docker-compose user.

## Problem

I'm using the [linuxserver/letsencrypt](https://hub.docker.com/r/linuxserver/letsencrypt) to expose all of my htpc "services" via subdomains: `sonarr.*`, `radarr.*` ([proxy-confs](https://github.com/linuxserver/reverse-proxy-confs) FTW), etc (already have a dynamic dns domain with valid SSL cert) and now I've tried to adopt this one `docker-rutorrent`.

**The thing is**, as I have exposed all my subdomains via the `linuxserver/letsencrypt` container, I would also like to expose rutorrent, from this container, from the same `linuxserver/letsencrypt`'s _nginx_ instance. 
I'm aware that this container already has an _nginx_ builtin, but I would rather have them all exposed from the `linuxserver/letsencrypt` container.

What I was trying to do, but it's not working, is, using `docker-compose`, mapping this container's port `80` to something like `8080` on my `docker-compose` setup, like the following:

<details>
<summary>rutorrent inside my docker-compose.yml</summary>

```docker
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=XXXX
      - PGID=XXX
    volumes:
      - /opt/docker/rutorrent/config:/config
      - /data:/downloads
    ports:
      - 8080:80  # 👈 here is the customization 
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
```

</details>

In my `proxy-confs/rutorrent.subdomain.conf` of the `linuxserver/letsencrypt` container I have something like this (basically, I've just customized the `8080` port [from it's original conf](https://github.com/linuxserver/reverse-proxy-confs/blob/master/rutorrent.subdomain.conf.sample)):

<details>
<summary>nginx rutorrent.subdomain.conf</summary>

```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name rutorrent.*; # 👈  using the rutorrent container name as expected

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth; # having this on/off is the same 🤷‍♂️ 
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_rutorrent rutorrent;
        proxy_pass http://$upstream_rutorrent:8080;
    }

    location /RPC2 { # not sure if I need to have this 🤔 
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_rutorrent rutorrent;
        proxy_pass http://$upstream_rutorrent:8080;
    }
}
```

</details>

With these confs, I'm always having a `502` bad gateway when accessing via my subdomain: e.g. `rutorrent.htpc.mydyndns.com`.
And checking the logs, I cannot understand why 😢.

**Note:** Although I cannot expose it via subdomain it works like a charm locally on `127.0.0.1:8080`, ofc 👌 

If anyone can help, I would really appreciate the help.
I'm already stuck for 3/4 days 😄 

Thanks in advance.

**Comment by aptalca** [comment]
You're not supposed to make any changes to the rutorrent proxy conf. Leave the port as 80.

It uses the container name as dns hostname to connect directly through the docker network, not through the host, therefore it uses the container port of 80 to connect, not the mapped host port of 8080.

As a rule of thumb, modify only the things that the confs/readme tell you to, nothing more, nothing less ;)

**Comment by crsantos** [comment]
Hi @aptalca, thanks for the comment.

> You're not supposed to make any changes to the rutorrent proxy conf. Leave the port as 80.

I didn't change anything from `rutorrent`'s nginx container, just the `proxy-confs` from `letsencrypt` container and the port mapping on my docker-compose: `8080:80`.

Look my rutorrent's nginx config (it's pristine, I guess):

`$ cat rutorrent/config/nginx/site-confs/default`

```nginx
upstream backendrtorrent {
    server unix:/run/php/.rtorrent.sock;
}

server {
    listen 80 default_server;

    listen 443 ssl;

    root /app/rutorrent;
    index index.php index.html index.htm;

    server_name _;

    ssl_certificate /config/keys/cert.crt;
    ssl_certificate_key /config/keys/cert.key;

    client_max_body_size 0;

    location / {
        location ~ .php$ {
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include /etc/nginx/fastcgi_params;
        }
    }

    location /RPC2 {
        access_log /config/log/nginx/rutorrent.rpc2.access.log;
        error_log /config/log/nginx/rutorrent.rpc2.error.log;
        include /etc/nginx/scgi_params;
        scgi_pass backendrtorrent;
    }
}
```

**Comment by aptalca** [comment]
I mean `proxy-confs/rutorrent.subdomain.conf`
Don't make any changes to it

**Comment by crsantos** [comment]
That would require me to do something like: `- 80:80` on my docker-compose's rutorrent entry. And that doesn't work.

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (f001386d4eab5c491b4d38e6165be4a5c1a33e823c55fb764948119b31450681): Bind for 0.0.0.0:80 failed: port is already allocated
```

That's why I mapped it as `- 8080:80`

**Comment by aptalca** [comment]
Read what I wrote above.

Do whatever port mapping you like for rutorrent in the docker compose. But do not change the rutorrent.subdomain.conf. Those two have nothing to do with each other. Because the proxy conf uses the container port

**Comment by crsantos** [comment]
😄 DAMN! 🎉 You're right, that's it!

```nginx
set $upstream_rutorrent rutorrent; # <- it's already using the container name 🤦‍♂️ 
proxy_pass http://$upstream_rutorrent:80;
```

Many thanks, and apologies for not getting this straight at the first time.

**Comment by aptalca** [comment]
Np, glad it works
