### ISSUE TITLE
Autounpack doesn't work

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-rutorrent#115]
Autounpack doesn't work, manual unpacking does. Using the usual wildcard: `/.*/`
There are no error logs or anything.

Host OS: Debian Buster
Command: `docker create --name rutorrent -e PUID=1001 -e PGID=1001 -p 3001:80 -p 5000:5000 -p 51413:51413 -p 6881:6881/udp -v /rutorrent:/config -v /downloads:/downloads --restart unless-stopped linuxserver/rutorrent`
Log: 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-nginx-fix: executing... 
Current version detected.
[cont-init.d] 10-nginx-fix: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Don't know how to debug this. Also checked the log files, but there weren't any errors there.

**Comment by natiz** [comment]
for me unpack doesn't work at all, and in rtorrent (GUI) logs:

```
[23.04.2019 20:16:40] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[23.04.2019 20:16:40] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[23.04.2019 20:16:40] create: Plugin will not work. It requires plugin(s) _task
[23.04.2019 20:16:40] unpack: Plugin will not work. It requires plugin(s) _task
[23.04.2019 20:16:40] mediainfo: Plugin will not work. It requires plugin(s) _task
[23.04.2019 20:16:40] screenshots: Plugin will not work. It requires plugin(s) _task
[23.04.2019 20:16:40] spectrogram: Plugin will not work. It requires plugin(s) _task
```

python is indeed missing (but who cares), however, pgrep seems to be there:
```
docker exec -it 73b0de673f05 bash
root@73b0de673f05:/# python
bash: python: command not found
root@73b0de673f05:/# pgrep
pgrep: no matching criteria specified
Try `pgrep --help' for more information.
root@73b0de673f05:/#
```

**Comment by ghost** [comment]
@natiz this is solved in #112

**Comment by natiz** [comment]
flawless, thanks @mgrandl

**Comment by maticks81** [comment]
you need to edit your config.php file adding in these two lines.
You should be able to find this file in config/rutorrent/settings/config.php

$pathToExternals = array(
"pgrep" => '/usr/bin/pgrep', // Something like /usr/bin/pgrep. If empty, will be found in PATH.
"python" => '/usr/bin/python3', // Something like /usr/bin/python3. If empty, will be found in PATH.

Then restart your docker and _task will pickup pgrep and unpack will work fine.

If you want to fix the _cloudflare issue you need to connect to the Docker Console and issue "apk add python3".

**Comment by sparklyballs** [comment]
@maticks81 , python3 is already added to the image.

https://github.com/linuxserver/docker-rutorrent/blob/master/Dockerfile#L28

the only fix required is to add the missing lines to config.php , or delete it entirely and restart the container, (providing you have not made any additional changes to the file, as those would be lost and need to be put back in).

**Comment by ghost** [comment]
@sparklyballs This doesn't answer the original issue though.

**Comment by sparklyballs** [comment]
with the latest pull of the image, and this as my run line

docker run --name=test -d -e PUID=1000 -e PGID=1000 -v /home/sparklyballs/test-config:/config -v /home/sparklyballs/test-downloads:/downloads -p 80:80 -p 5000:5000 -p 51413:51413 -p 6881:6881/udp linuxserver/rutorrent

and the only option changed in the webui settings being to enable autounpack i have just downloaded a torrent and it has unpacked it into the incoming folder alongside the original rar files.

**Comment by ghost** [comment]
mhm alright weird. thanks for testing it out though.
