### ISSUE TITLE
Python is missing 

### ISSUE THREAD

**Issue by Blackdixxa** [linuxserver/docker-rutorrent#118]
_Cloudflare plugin refuse to load

I have to do a :
"apk add python && apk add python3"
to have all the plugins loading.

**Comment by sparklyballs** [comment]
update the image , because python3 was added to the image fairly recently.

**Comment by Blackdixxa** [comment]
Well ok since it wasn't working I wasn't updating the image guess we can close the issue which isn't an issue anymore.
