### ISSUE TITLE
Add client_body_temp_path to default NGINX config

### ISSUE THREAD

**Issue by Ben-Atherton** [linuxserver/docker-rutorrent#119]
I get the following in my NGINX error log file from time to time

```
[crit] 326#326: *14294 open() "/var/tmp/nginx/client_body/0000000006" failed (13: Permission denied), client: XX.X.XX.XXX, server: _, request: "POST /php/addtorrent.php? HTTP/1.1", host: "mydomain.com:8080"
```

After a bit of research I added the following to my NGINX config file and so far seems to be holding up

```
client_body_temp_path /var/tmp/nginx/client_body 1 2;
```

Should this be added to this image?

**Comment by aptalca** [comment]
This is an elusive nginx bug that affects a very small subset of users. We have been unable to reproduce it, so we can't troubleshoot. The workaround is to set the temp path location to a folder under /config (the folder you selected is the same folder nginx already has it set to, so not sure if what you did really had any effect)

Currently we are not planning on trying to fix it at the image level (as the fix can easily be applied by the affected users), but if we do so in the future, it will likely be through our nginx baseimage
