### ISSUE TITLE
"filemanager" plugin

### ISSUE THREAD

**Issue by abeksis** [linuxserver/docker-rutorrent#127]
I installed the file manager plugin under Docker. There were some problems and with the help of the microdu70 I was able to. but there is a problem

`[06.07.2019 06:05:04] FILE MANAGER: Failed to get directory contents : /`
from:
`$ fm ['tempdir'] = '/tmp';`
to:
`$ fm ['tempdir'] = '/config/rutorrent/profiles/tmp';`

But no error file "errors.log"

info:
1. Docker image - https://hub.docker.com/r/linuxserver/rutorrent/

2. unraid server.

**Comment by CHBMB** [comment]
Closing this as it isn't a bug.
