### ISSUE TITLE
rTorrent crashes after a few minutes on Alpine 3.10

### ISSUE THREAD

**Issue by yitzhaq** [linuxserver/docker-rutorrent#128]
In the latest image, with Alpine 3.10, rTorrent crashes after running just a few minutes, producing the following, not particularly detailed log output:

```
1563273685 C Caught signal: 'Illegal instruction.
---DUMP---
Caught Illegal instruction, dumping stack:
Stack dump not enabled.

---END---
```
Switching to v3.9-ls45, the last release before the rebase from Alpine 3.9, everything works swimmingly, just as before. Presumably one of the numerous new package versions is causing this, though I couldn't begin to guess which one.

Environment is Synology DS-1815+ (avoton) x86_64 running DSM 6.2.2-24922 Update 2:

# docker --version
Docker version 17.05.0-ce, build 371caef-synology

**Comment by thelamer** [comment]
I cannot duplicate this on my system. 
I fired up and added 10 Linux ISOs, they downloaded and have been seeding for 30 minutes now. 
Can you duplicate this on a clean container  and a clean config ?

**Comment by ghost** [comment]
This might be related to the recent rtorrent release from 3 days ago, they bumped the min version needed of libtorrent, after that rutorrent has a bugfix for this release but it's not in the docker image yet

**Comment by thelamer** [comment]
Me and no one on the team can duplicate this. I am closing this issue.
