### ISSUE TITLE
rutorrent is incompatible with rtorrent

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-rutorrent#129]
Sorry for not following template, can you kick off a manual build?

rutorrent was updated to fix the recent (3 days ago) release of rutorrent but the docker images haven't been rebuilt yet to get an updated rutorrent. As of now rutorrent cannot communicate with rtorrent.

**Comment by ghost** [comment]
@LinuxServer-CI rebuild

**Comment by tobbenb** [comment]
The last release of rutorrent is 3.9 and was released in April. That is the one we built.

**Comment by aptalca** [comment]
Our build process is automated. Shortly after a new release, our jenkins pushes a new build

**Comment by ghost** [comment]
Oh then there needs to be a change where it pulls rutorrent from master because this could happen again.

Rutorrent needs to make a release, that would be 'proper' but the alternative is to update from master.

rutorrent right now does not work as is, been getting lots of complaints since the image update

**Comment by aptalca** [comment]
Then it probably needs a new upstream release with fixes. In the meantime, you can go back to an older image via docker image tags

**Comment by ghost** [comment]
@aptalca I filed an issue with rutorrent https://github.com/Novik/ruTorrent/issues/1919

**Comment by aptalca** [comment]
Thanks, we'll follow that

**Comment by aptalca** [comment]
@LooseSeal2 I should have looked into this more closely.

We still package rtorrent 0.9.7 from alpine repos, which hasn't changed in months. I just spun up a fresh rutorrent container and don't see any issues with rtorrent connection

**Comment by nomandera** [comment]
As per offline discussion we should split this container into two, rtorrent and rutorrent.

Docker have long since solved the issue with screen which originally played a big part in the decision for this multi app container but there is no need any more.

Two would be a better fit with our design policy. There are plenty of people who want rtorrent ncurses only for all the obvious reasons.

**Comment by thelamer** [comment]
I do not see a compelling reason to keep this issue open, the latest version of this container functions.
