### ISSUE TITLE
Autotools plugin does not work until Web UI is opened for first time

### ISSUE THREAD

**Issue by janbo208** [linuxserver/docker-rutorrent#133]
The Autotools plugin doesn't work with a new or restarted container until the Web UI is opened for the first time. Torrents that are added before that will have no label and won't be moved.

The issue seems to be caused by this line in the rtorrent config file: 

https://github.com/linuxserver/docker-rutorrent/blob/13ab52152de2d9446e2497b1e827b25573c473df/root/defaults/rtorrent.rc#L1

According to the rutorrent documentation (https://github.com/Novik/ruTorrent/wiki/Plugins#starting-plugins-with-rtorrent) the command should be `execute2`. The path to the startup script also seems to be outdated. 

So I changed the line in my config file to this:
~~~
execute2 = {sh,-c,/usr/bin/php7 /app/rutorrent/php/initplugins.php &}
~~~

Unfortunately this still doesn't work. 

Manually running `/usr/bin/php7 /app/rutorrent/php/initplugins.php &` inside the container actually works.

**Comment by Negwoh** [comment]
Autotools appear to not work at all for me? I am confident I am doing something wrong...

**Comment by golya87** [comment]
For me the history and ratio group plugin doesn't work (I'm not using the autotool), until I open the webGUI. Changing the execute command in the rtorrent.rc file to (`execute2 = {sh,-c,/usr/bin/php7 /app/rutorrent/php/initplugins.php abc &}`) didn't help.

Update: tried Autotool on RPi4 with latest container, no luck.

**Comment by Superpiffer** [comment]
You have to change the default settings because initplugins.php script is not there anymore from this commit: https://github.com/linuxserver/docker-rutorrent/commit/d120f66014bda78349fac84d4f876924bd0aec53  Here's the correct setting:

> execute2 = {sh,-c,/usr/bin/php /app/rutorrent/php/initplugins.php abc &}

Of course if you use another user, you have to write it instead of "abc", maybe that's the problem.
