### ISSUE TITLE
rtorrent only docker image

### ISSUE THREAD

**Issue by carpenike** [linuxserver/docker-rutorrent#134]
Would there be any interest by the linuxserver team to split off rtorrent from rutorrent and manage a parallel docker image that only contains rtorrent and XMLRPC? Looking at a microservice approach within Kubernetes that integrates with other docker containers which house the other components -- rutorrent, flood, etc.

**Comment by carpenike** [comment]
@sparklyballs, what are your thoughts?

**Comment by aptalca** [comment]
That's not in the cards right now. None of the team members are real excited about rutorrent at the moment.

You can post image requests on our forum.

**Comment by carpenike** [comment]
@aptalca -- Understood. Not to split hairs, but this was specific to rtorrent as I/we aren't excited about rutorrent either. Decoupling the UI from the download service allows additional flexibility and doesn't require rutorrent to be managed either.

**Comment by aptalca** [comment]
What I meant to say was most of the team members moved onto qbittorrent or another alternative so they are not really interested in investing time into rtorrent/rutorrent. But I'll bring it up with them nonetheless.

**Comment by carpenike** [comment]
Ah, got it. Thanks.
