### ISSUE TITLE
ruTorrent is not deleting data when ask to remove and delete data.

### ISSUE THREAD

**Issue by kanedauy** [linuxserver/docker-rutorrent#136]
## Expected Behavior
ruTorrent should remove the torrent from the list of torrents and delete the associated data when I select remove and delete data.

## Current Behavior
Only the torrent is removed from the list

## Command used to create docker container
```
docker create \
  --name=rutorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 8080:80 \
  -p 5000:5000 \
  -p 51413:51413 \
  -p 6881:6881/udp \
  -v /rutorrent/config:/config \
  -v /bitTorrent:/downloads \
  --restart unless-stopped \
  linuxserver/rutorrent
```
## Environment
Raspberry Pi 4
Raspbian GNU/Linux 10 (buster) 

I don't see any issue with file permissions, all the users are the same as the abc,  and I have the execute = {sh,-c,/usr/bin/php7 /usr/share/webapps/rutorrent/php/initplugins.php abc &} in the rtorrent.rc

The main issue is that happens sometimes, it seems to happen for big torrents more often.

Any Idea?

**Comment by andressuy** [comment]
**NOTE:** 
This seems to happen after a container restart, for a time it does not work, but after a couple of days of usage it starts working.
