### ISSUE TITLE
unpack doesn't always unpack the downloaded torrents.

### ISSUE THREAD

**Issue by kkasberg** [linuxserver/docker-rutorrent#137]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

I expect that rar or zip files will be extracted once downloaded, but they are not sometimes, and the docker container needs to be restarted.
------------------------------

## Expected Behavior

Extraction should happen.

## Current Behavior

rar files sit and are not extracted.

## Steps to Reproduce

Occasionally it happens.

## Environment
**OS:**    ubuntu 18.04  
**CPU architecture:** X86_64      
**How docker service was installed:**
      using the example on dockerhubs page.

**Comment by nebb00** [comment]
I am also getting this problem

**Comment by j0nnymoe** [comment]
Closing issue due to ask. please re-open a new issue if this still a problem.
