### ISSUE TITLE
[enhancement] provide notice about custom plugins

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [linuxserver/docker-rutorrent#138]
currently, to add custom plugins, you have to add them to ``/path/to/config/mount/plugins``.
this should be mentioned in the readme.

**Comment by kanedauy** [comment]
Can you point me to the config that have this setting in the container?
Thanks a lot.

**Comment by drizuid** [comment]
> Can you point me to the config that have this setting in the container?
> Thanks a lot.

@kanedauy if you need support with containers, please post on the forums or join us in discord. This isn't the appropriate place to request help.
