### ISSUE TITLE
plugin settings do not persist on container restart

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [linuxserver/docker-rutorrent#139]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
they should be persisted

## Current Behavior
they aren't

## Steps to Reproduce

1. set settings for a plugin, i.e. autotools
2. restart container

this is due to the fact that rutorrent [stores plugin configurations in the rutorrent app directory itself](https://github.com/Novik/ruTorrent/wiki/Config), and not in the configuration directory.

**Comment by jeff47** [comment]
Has there been any progress on this?  I don't want to have to set up my autotools etc every time the container restarts.  Maybe move the rutorrent app directory to a volume instead?

**Comment by seanatrons** [comment]
try adding to rtorrent.rc `execute2 = {sh,-c,/usr/bin/php /var/www/localhost/rutorrent/php/initplugins.php your_user_name &}`
