### ISSUE TITLE
How to protect by a password ?

### ISSUE THREAD

**Issue by vipera7** [linuxserver/docker-rutorrent#142]
I found the following issue https://github.com/linuxserver/docker-rutorrent/issues/74 but there is no concrete answer.

How can we protect by a username and a password rutorrent ?

**Comment by vipera7** [comment]
Fixed with `sudo htpasswd -c /path/to/rutorrent/config/.htpasswd foouser`

And add the following to nginx/site-confs/default in the server block : 

```
auth_basic           "Administrator’s Area";
auth_basic_user_file /conf/.htpasswd;
```

And restart the container

**Comment by archont94** [comment]
> sudo htpasswd -c /path/to/rutorrent/**config**/.htpasswd foouser

> auth_basic_user_file /**conf**/.htpasswd;

On second command there is typo, it should be
auth_basic_user_file /**config**/.htpasswd;
