### ISSUE TITLE
Most torrents are not finished

### ISSUE THREAD

**Issue by albertusQuelle** [linuxserver/docker-rutorrent#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Torrents stuck at ~95%
------------------------------

## Expected Behavior
Torrents should finish and have final state 100% completion 

## Current Behavior
Most torrents (seems that it hits torrents > 1,5GB size)  stuck and dont complete. 

## Steps to Reproduce

1. Upload new torrent

## Environment
**OS:**      Synology DSM 6.2.2
**CPU architecture:** x86_64/arm32/arm64      64Bitarm DS 918+
**How docker service was installed:**      
With package Manager

## Command used to create docker container (run/create/compose/screenshot)
no comand, just per GUI
![image](https://user-images.githubusercontent.com/2970225/71576700-c5aaa000-2af1-11ea-8ece-94aa8f6978de.png)

## Docker logs
Checked the rtorrent logs in /logs/config/rtorrent

`1577739829 E Could not resume download: Could not create directory '/downloads/myDownloadFolder': Permission denied
`

**Comment by andressuy** [comment]
Seems to be a permission problem, are you setting the PUID and PGID?

**Comment by j0nnymoe** [comment]
@lordvalium You need to provide more information. What folders are you mounting? what PUID/PGID are you setting?

**Comment by albertusQuelle** [comment]
fixed it was a selfmade cronjob problem
