### ISSUE TITLE
ruTorrent cannot determine the UID of rTorrent user.

### ISSUE THREAD

**Issue by golya87** [linuxserver/docker-rutorrent#149]
## Current Behavior
After I've upgraded to v3.9-ls73 or 74 I get the following errors in rutorrent webGUI log:
```
[26.02.2020 00:15:42] ruTorrent cannot determine the UID of rTorrent user. Some functionality will be unavailable.
[26.02.2020 00:15:42] rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory ().
```

If I click on the settings icon in webGUI:
`[26.02.2020 00:18:12] Bad response from server: (500 [error,getsettings]) Warning: XMLRPC call is failed.`

It is a full vanilla non configured container.

## Environment
**OS:**      Debian Buster
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)
`docker run --rm --name=rutorrent_new -p 800:80 -p 25251:25252 -e PGID=1111 -e PUID=1007 -v /strg/docker/rutorrent_new:/config -v /strg/free:/downloads/free -e TZ=Europe/Budapest linuxserver/rutorrent:v3.9-ls73`

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1007
User gid:    1111
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-nginx-fix: executing...
Current version detected.
[cont-init.d] 10-nginx-fix: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
..........+++++
..................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
'access-swap.sh' -> '/config/rutorrent/settings/access-swap.sh'
'access.ini' -> '/config/rutorrent/settings/access.ini'
'access_no' -> '/config/rutorrent/settings/access_no'
'access_yes' -> '/config/rutorrent/settings/access_yes'
'config.php' -> '/config/rutorrent/settings/config.php'
'plugins.ini' -> '/config/rutorrent/settings/plugins.ini'
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Comment by golya87** [comment]
With v3.9-ls72, I got no problem.

**Comment by Halfwalker** [comment]
Confirmed - same issue with Ubuntu 18.04 with 5:19.03.6~3-0~ubuntu-bionic, and with Ubuntu 12.04 (!! - just testing) with 17.04.0~ce-0~ubuntu-precise

**Comment by Superpiffer** [comment]
Using rutorrent beta version (https://github.com/Novik/ruTorrent/releases/tag/v3.10-beta) solves the problem.

**Comment by adamwinn** [comment]
> Using rutorrent beta version (https://github.com/Novik/ruTorrent/releases/tag/v3.10-beta) solves the problem.

@Superpiffer
How do you use the beta version?

**Comment by Superpiffer** [comment]
> > Using rutorrent beta version (https://github.com/Novik/ruTorrent/releases/tag/v3.10-beta) solves the problem.
> 
> @Superpiffer
> How do you use the beta version?

As a temporary fix:

- Clone this git repo:
`git clone https://github.com/linuxserver/docker-rutorrent.git`
- Build the container with a build-arg, in order to select the correct rutorrent version, and tag it as you want (i.e. "beta"):
`docker build --build-arg RUTORRENT_RELEASE="v3.10-beta" -t linuxserver/rutorrent:beta .`
- Use the new image in your docker-compose file or in your startup command:

```
version: "2"
services:
  rutorrent:
    image: linuxserver/rutorrent:beta
    container_name: rutorrent
[...]
```

**Comment by golya87** [comment]
The workaround suggested by Superpiffer has solved my problem.

**Comment by golya87** [comment]
The mentioned pull request (#150) solved my problem.
