### ISSUE TITLE
Exposed ports

### ISSUE THREAD

**Issue by shemdk** [linuxserver/docker-rutorrent#15]
The readme says

> -p 80:80 -p 5000:5000 \
> -p 51413:51413 -p 6881:6881/udp \

but according to the dockerfile and docker inspect only port 80 is exposed.

**Comment by tobbenb** [comment]
The port doesn't need to be exposed in the dockerfile to work. As long as you add the -p 5000:5000 or any other port to the docker run command it will work.

**Comment by shemdk** [comment]
OK, wasn't aware of that, thanks. Just getting started with docker ;). Closing issue.
