### ISSUE TITLE
GeoIP is not working (wget: bad address). 

### ISSUE THREAD

**Issue by ge-ho** [linuxserver/docker-rutorrent#154]
## Current Behavior
GeoIP plugin is not working. Logs say the following:

## Docker logs

wget: bad address 'geolite.maxmind.com',
run-parts: /etc/periodic/monthly/geoip: exit status 1

**Comment by triqster1** [comment]
I highly suggest using a different rutorrent image. There are so many outstanding issues with this one and it's clear that the "maintainers" don't give a flying fuck about it if you have a look at all the ignored issues. Avoid.

**Comment by crstian19** [comment]
> I highly suggest using a different rutorrent image. There are so many outstanding issues with this one and it's clear that the "maintainers" don't give a flying fuck about it if you have a look at all the ignored issues. Avoid.

Which image are you using? I'm looking for a new one.
