### ISSUE TITLE
Please update xmlrpc-c in docker image

### ISSUE THREAD

**Issue by lukedoomer** [linuxserver/docker-rutorrent#158]
Because there is an annoying bug which produce weird console output. please see [here](https://github.com/Entware/Entware/issues/427) and [here](https://github.com/rakshasa/rtorrent/issues/683)
You will need to update xmlrpc-c to at least version 1.51.05 which contains a [fix](https://sourceforge.net/p/xmlrpc-c/code/3068/) for this issue.

**Comment by V33m** [comment]
The xmlrpc-c version is currently at [xmlrpc-c-1.51.06-r0](https://github.com/linuxserver/docker-rutorrent/blob/2cc7f0d2eb970cfcceed06f5b8faafb2d6b17700/package_versions.txt#L160), hence the issue can be closed.
