### ISSUE TITLE
Some RSS feeds are broken because Snoopy adds port number 80 to Host headers

### ISSUE THREAD

**Issue by hufman** [linuxserver/docker-rutorrent#159]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Rutorrent should be able to load all RSS feeds and download from them.

## Current Behavior

Rutorrent is unable to load RSS data from http://www.gamemp3s.net/feed/
From a packet trace, Rutorrent's Snoopy client provides an incorrect Host header, which gets redirected to the same URL, in a loop until Rutorrent gives up and fails with an cantFetchRSS error.
```
GET /feed/ HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
Host: www.gamemp3s.net:80
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*
Accept-encoding: gzip

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 12 May 2020 03:21:41 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
X-Pingback: http://www.gamemp3s.net/wp/xmlrpc.php
Last-Modified: Fri, 17 Apr 2020 21:50:03 GMT
ETag: "50c7baa86f1f1fc2198cb522d3d69804"
Location: http://www.gamemp3s.net/feed/
```

The behavior was changed in [this commit](https://github.com/linuxserver/docker-rutorrent/commit/ba85d293c0c931491e9aa0c7dd3f01fc18282215). The [upstream Snoopy code](https://github.com/Novik/ruTorrent/blame/d286d167611d81a8aa887e31bb5b8458e03a58cc/php/Snoopy.class.inc#L349) does not add this port number, and editing the file inside the instance to match makes the fetch work.

The commit is not linked to any bug to provide context on why the behavior was changed.

## Steps to Reproduce

1. Start the Rutorrent Docker image
2. Try to add a new RSS feed using the URL http://www.gamemp3s.net/feed/ 
3. After ~10 seconds, a popup appears saying it failed

## Environment
**OS:**  Alpine Linux
**CPU architecture:** x86_64      
**How docker service was installed:**      

apk install docker

## Command used to create docker container (run/create/compose/screenshot)

`docker run -d -p 80 --restart unless-stopped -v rtorrent_config:/config -v rtorrent_downloads:/downloads -e PUID=123 -e PGID=1005 linuxserver/rutorrent`

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    123
User gid:    123
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-nginx-fix: executing...
Current version detected.
[cont-init.d] 10-nginx-fix: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by drizuid** [comment]
https://github.com/Novik/ruTorrent/issues/1247
