### ISSUE TITLE
pm.max_children configuration

### ISSUE THREAD

**Issue by Legogris** [linuxserver/docker-rutorrent#160]
Hello and thanks for the great job.

I noticed that the webui has intermittent issues (this is just on a single user instance, just a couple of torrents).

I see the following in `/config/log/php/error.log`:
```
WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

It seems like the default value should be set higher, especially with the default `pm = dynamic`. The value is set in `/etc/php7/php-fpm.d/www.conf`.

I would submit a PR, but I am not sure what the preferred approach for this from the maintainers is - whole config in `/root/etc` or a pach in `/patch`?

**Comment by aptalca** [comment]
you can manually edit `/config/php/www2.conf`

**Comment by j0nnymoe** [comment]
Closing issue as assuming this is closed due to no response. please re-open a new issue if this still a problem.
