### ISSUE TITLE
Themes don't appear in rutorrent

### ISSUE THREAD

**Issue by v9999** [linuxserver/docker-rutorrent#163]
If I add themes to rutorrent\rutorrent\plugins\theme\themes or rutorrent\rutorrent\plugins\theme, they don't appear in the dropdown menu.

Expected behaviour should be that they'd be automatically imported by the theme plugin, as explained in the official wiki for rutorrent: https://github.com/Novik/ruTorrent/wiki/PluginTheme

Also, darkbetter theme doesn't work:
`2020/05/31 13:12:13 [error] 345#345: *3062 open() "/app/rutorrent/plugins/theme/themes/DarkBetter/images/desc.gif" failed (2: No such file or directory), client: 192.168.100.67, server: _, request: "GET /plugins/theme/themes/DarkBetter/images/desc.gif HTTP/1.1", host: "192.168.100.79:81", referrer: "http://192.168.100.79:81/"`

**Comment by triqster1** [comment]
I highly suggest using a different rutorrent image. There are so many outstanding issues with this one and it's clear that the "maintainers" don't give a flying fuck about it if you have a look at all the ignored issues. Avoid.
