### ISSUE TITLE
Settings not being saved after a container restart

### ISSUE THREAD

**Issue by albertodiazsaez** [linuxserver/docker-rutorrent#170]
When I change some settings (I checked the 
"Downloads" settings under the cog) in the WebGUI of ruTorrent, I noticed they where not being saved after a restart of the container.

------------------------------

## Expected Behavior
Settings that have changed must be saved after restarting the container.

## Current Behavior
Settings are the default ones after a reset.

## Steps to Reproduce

1. Go to the "Settings Cog", Downloads section.
2. Change the settings for anything in this tab.
3. Click "OK".
4. Restart the container.
5. Go to the settings you have changed, the default ones appear.

## Environment
**OS:** Fedora 31 (Server Edition)
**CPU architecture:** x86_64
**How docker service was installed:** I don't remember, but I can give you any information that is useful for this.

## Command used to create docker container (run/create/compose/screenshot)

Docker Compose in /home/docker/rutorrent. User "docker" is 1001:1001

[docker-compose.txt](https://github.com/linuxserver/docker-rutorrent/files/4941684/docker-compose.txt)

## Docker logs

[rutorrent-log.txt](https://github.com/linuxserver/docker-rutorrent/files/4941685/rutorrent-log.txt)

As additional note, the config folder is being created, and there is config inside, but I don't know where to search the config that I change.

**Comment by j0nnymoe** [comment]
https://github.com/Novik/ruTorrent/wiki#some-non-obvious-points
```rtorrent Settings, changed by the user through the "Settings" panel in ruTorrent, are valid until rtorrent restart. After which all settings will be set according to the rtorrent config file (.rtorrent.rc).```

**Comment by albertodiazsaez** [comment]
Oh, sorry, I read trough all issues and searched about the problem and I missed that point in the wiki... I feed dumb >.<

Thank you very much! ^·^
