### ISSUE TITLE
Get "php/getplugins.php" aborts during transmission

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [linuxserver/docker-rutorrent#172]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

`Get php/getplugins.php`

------------------------------

## Expected Behavior

Normal response.

## Current Behavior

Chrome says 200 but content-length mismatch.
curl: (18) transfer closed with 199878 bytes remaining to read.

## Steps to Reproduce

1. curl "server_name/php/getplugins.php"
2. curl: (18) transfer closed with (some random number) bytes remaining to read.

## Environment
**OS: **  Linux Docker on Synology
**CPU architecture:** x86_64
**How docker service was installed:**      Use Synology Docker service GUI

## Fix

I don't know where this file is so I have to submit an issue here. It locates under `/config/nginx/site-confs/default` on a running docker.

```
# configuration file /config/nginx/site-confs/default:
upstream backendrtorrent {
    server unix:/run/php/.rtorrent.sock;
}

server {
    listen 80 default_server;

    listen 443 ssl;

    root /app/rutorrent;
    index index.php index.html index.htm;

    server_name _;

    ssl_certificate /config/keys/cert.crt;
    ssl_certificate_key /config/keys/cert.key;

    client_max_body_size 0;

    location / {
        location ~ .php$ {
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
    
######################### Adding these two lines to fix this problem
            fastcgi_buffers 8 16k;       
            fastcgi_buffer_size 32k;
#########################

            include /etc/nginx/fastcgi_params;
        }
    }

    location /RPC2 {
        access_log /config/log/nginx/rutorrent.rpc2.access.log;
        error_log /config/log/nginx/rutorrent.rpc2.error.log;
        include /etc/nginx/scgi_params;
        scgi_pass backendrtorrent;
    }
}
```

## Command used to create docker container (run/create/compose/screenshot)

Just normal startup

**Comment by opcon** [comment]
I had the same issue & fixed it by clearing the cache - perhaps that'll help?

**Comment by jqqqqqqqqqq** [comment]
> I had the same issue & fixed it by clearing the cache - perhaps that'll help?

Can you provide steps to clear the cache?
