### ISSUE TITLE
Way to avoid  subfolders creation ?

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [linuxserver/docker-rutorrent#173]
Hi,

I read your documentation and this annoy me : 
**It should also be noted that this container when run will create subfolders ,completed, incoming and watched in the /downloads volume.**

Do we have a way to avoid this behavior, if yes, how ? I did try some search and configuration tweak, but didn't succeed, it's to be noted that i'm a r(u)torrent newbie, I'm from the Transmission world :)

Thank you in advance

**Comment by aptalca** [comment]
You can try this: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by BetterToAutomateTheWorld** [comment]
Hi, that's exactly what I wanted to avoid :) (diverge from the master image)

But if no solution can be proposed (r(u)torrent configuration for example ? I'm not familiar with r(u)torrent)...

Anyway, thank you for your answer

**Comment by adri24an** [comment]
i'm interested in this too! is it possible via rtorrent.rc?

**Comment by BetterToAutomateTheWorld** [comment]
I didn't dig yet for a solution, I'm curious if someone found something, let me know ! :)
