### ISSUE TITLE
DNS caching in container

### ISSUE THREAD

**Issue by tekand** [linuxserver/docker-rutorrent#174]
Feature request for DNS caching
------------------------------

## Expected Behavior
If you are running multiple torrents from the same tracker (same host) and they update almost simultaneously (within TTL record of DNS), then only one query is done to the DNS server, the rest of the queries are served from the local cache.

## Current Behavior
Each tracker update for each torrent results in a separate DNS request.

## Environment
Independent of the environment. 

## Command used to create docker container (run/create/compose/screenshot)
N/A

## Docker logs
N/A

**Comment by drizuid** [comment]
We do not offer a dns server within the container, a caching dns server would be your responsibility to setup and maintain for your network and would not make sense to put into every torrent container we have.

**Comment by tekand** [comment]
It would make sense. Just imagine that you are running 200 torrents from the same tracker. This way 200 dns requests will be sent to the network's caching dns server for the same domain. Wouldn't it be better to have this caching dns server right in the container? So that these redundant requests are not leaving the container at all?

**Comment by drizuid** [comment]
As I stated, we will not be adding caching dns servers to our containers. You may modify it to suit your needs by following our customization guidance at https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
