### ISSUE TITLE
Increase PHP number of file uploads

### ISSUE THREAD

**Issue by pathetic-lynx** [linuxserver/docker-rutorrent#183]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Uploading a large amount of torrent files at once should work

## Current Behavior
Only the first X files are actually uploaded and added as torrent due to PHP setting

## Steps to Reproduce
1. Select 30+ files to add as torrent
2. Upload
3. Not all of them are added

## Environment
**OS:** Arch
**CPU architecture:** x86_64
**How docker service was installed:** official repo

**Comment by aptalca** [comment]
you can edit the php settings via 2 files in `/config/php/`

**Comment by pathetic-lynx** [comment]
I know, but I think it would make sense to change the default value

**Comment by aptalca** [comment]
What should we make it? 10, 100, 10000? Everyone has a different idea on the right number. You're the first person who complained about this over the years, so our default must be good enough for the great majority. 
It's user customizable; you can set it to whatever you like.

**Comment by mabushey** [comment]
> It's user customizable; you can set it to whatever you like.

There are two files in config/php: `php-local.ini` and `www2.conf`. What would have to be added to them? Not very `user customizable` when nothing is documented.
