### ISSUE TITLE
add auth method into rutorrent

### ISSUE THREAD

**Issue by lollko** [linuxserver/docker-rutorrent#184]
Hi guys, 

It is possible add auth method (like .htaccess on apache2)  to container ? 

im using arm64v8 platform , but alpine linux is not my friend :(

**Comment by aptalca** [comment]
You can reference .htpasswd in the default nginx site config

**Comment by lollko** [comment]
that's fine, but if I update to a newer container I'll have to edit again?

**Comment by aptalca** [comment]
no, the default site config doesn't get overwritten during updates

**Comment by lollko** [comment]
thx :) problem solved
