### ISSUE TITLE
LOOKING FOR A MAINTAINER

### ISSUE THREAD

**Issue by j0nnymoe** [linuxserver/docker-rutorrent#188]
We are looking for a community maintainer for this image. The team members don't have the bandwidth or the interest in fixing and maintaining this image.

Anyone interested can reach out here or on our discord. If we are unable to find a maintainer within the next few weeks, this image will be deprecated.

Thanks

**Comment by o6uoq** [comment]
This has been the best, easiest and most performant flavour of `docker-rutorrent` I've used to date. I hope you find another maintainer! Sadly I'm not in a position to propose myself.

**Comment by mabushey** [comment]
I would consider taking this over >> IF << I could make it work. rtorrent is unusable, according to my stopwatch it took 2 minutes 28 seconds to refresh the ncurses gui from pressing 1, but cursor down does the same. While rtorrent was never even close to usable in the CLI GUI, The torrenting via rutorrent was originally working quite well for me, but then I added a bunch of torrents and now it's permanently 0/0 up down. The weird part is rutorrent is completely responsive. My i7 isn't the latest but I would hope it would be powerful enough to run rtorrent. First thing is I would replace screen with tmux, the only advantage screen has over tmux is it can act as a serial console, which is not needed/used here.

**Comment by j0nnymoe** [comment]
We will continue with dropping support with this container in due course. We will be recommending current users to migrate to CrazyMax's rutorent cotainer: https://github.com/crazy-max/docker-rtorrent-rutorrent/

@mabushey Thank you for the comment :) with what you mentioned, I think it's best to use CraxyMax's container as a replacement.

**Comment by urbanracer34** [comment]
Will there be any assistance in helping unraid users to migrate to the new container from this one?

**Comment by j0nnymoe** [comment]
I don't think we plan to create any unraid specific documentation but likely will create generic info on which folders map to which on the new container.
