### ISSUE TITLE
Allow customisation of cron log level

### ISSUE THREAD

**Issue by djmattyg007** [linuxserver/docker-rutorrent#27]
Currently the log level is hard coded to `0`. I would like to change it to `5` without having to edit existing config files. I don't need the verbosity that log level `0` provides.

I would like to submit a PR for this, and was thinking that an environment variable would be the best way of going about this. Before I went ahead and implemented it, I wanted to get the thoughts of the maintainers. Is this a good way of going about it? If so, what shoukd the variable be named? If not, what is a better idea?

**Comment by aptalca** [comment]
Sorry, just saw this. Where is the loglevel hardcoded? In rutorrent or nginx? and which file?

I'll take a look.

Thanks

**Comment by djmattyg007** [comment]
Line 3 of this file:
https://github.com/linuxserver/docker-rutorrent/blob/master/root/etc/services.d/cron/run#L3

**Comment by aptalca** [comment]
That is just the cron log verbosity and the only things run by cron are daily logrotate and a monthly geoip download. Do they generate a lot of noise?

I'm currently investigating. . .

**Comment by djmattyg007** [comment]
Yes, it runs once every minute and generates a minimum of at least 5 lines of output for each run.

**Comment by aptalca** [comment]
Can you post a log or a snippet? I have been running it for 24 hours and I don't see anything in the logs

Thanks

**Comment by djmattyg007** [comment]
Here's a sample of the log output: https://gist.github.com/djmattyg007/6752ce0ca71a476ca33c8b42ebf27e6b
When the log level is set to `5` instead of `0`, all of the `line run-parts` lines do not appear.

**Comment by aptalca** [comment]
Log level will be changed in a future update, but for the life of me I cannot figure out where you're seeing that output. Crond is set to output to syslog, which the docker log captures (there is no syslog daemon in the alpine baseimage). I'm not seeing any of those messages and I tried it on unraid (slackware), ubuntu and LibreELEC (JeOS).

What platform are you running this on and what is the docker version? And how exactly are you getting that log output? Through `docker logs rutorrent`?

**Comment by djmattyg007** [comment]
I'm actually running the container as a systemd-nspawn container. The logs are ending up in the systemd journal. I didn't think it would make such a big difference to what was going on.

**Comment by aptalca** [comment]
Ahh, the systemd journal. Thanks, that's good to know. Anyway, the log level has been changed in the last update.
