### ISSUE TITLE
Add Material Theme to ruTorrent

### ISSUE THREAD

**Issue by onedr0p** [linuxserver/docker-rutorrent#29]
The best theme out there:

https://github.com/Phlooo/ruTorrent-MaterialDesign

**Comment by dewey** [comment]
You can just add this to your Dockerfile if you want:

https://github.com/dewey/docker-rutorrent/commit/5f937c3f1f826e2433b108eaeef011ea691e2684

**Comment by onedr0p** [comment]
My understanding of docker though is.. if the container is updated (by linuxserver.IO) you'll use those settings.

Is it best to just have custom docker files and skip using theirs? Sorry I'm new to docker.

**Comment by onedr0p** [comment]
Thanks I added a PR to this dockerfile.
