### ISSUE TITLE
Allow custom themes by exposing theme directory of rutorrent

### ISSUE THREAD

**Issue by onedr0p** [linuxserver/docker-rutorrent#36]
Would be rad, thank you.

**Comment by cove45** [comment]
Would really like to see #42 merged please.

**Comment by lucasdcrk** [comment]
I'd like to have custom themes too

**Comment by onedr0p** [comment]
Given its been two years since I opened this, about a year since a PR was open, and the other issues with this image @sparklyballs does not care about this project. You might as well move on to another image or build it yourself. I appreciate lsio images however some of their maintainers are deaf to community contributions and feedback.

I'm closing this issue, feel free to open one if you want to be ignored like the rest of us.

**Comment by alex-phillips** [comment]
I am currently rewriting the container and it will include custom theme support. See the "rewrite" branch. I imagine it should be released soon.

**Comment by onedr0p** [comment]
Thanks for the update @alex-phillips :)
