### ISSUE TITLE
100% rTorrent Usage on HTTPS Tracker Timeouts 

### ISSUE THREAD

**Issue by ChromoX** [linuxserver/docker-rutorrent#38]
Using LibreSSL seems to cause problems with curl HTTPS tracker timeouts. Once rTorrent gets pegged to 100% it doesn't respond to rutorrent or RPC2.

curl seems to be linked to LibreSSL in Alpine.

This bug is related to: 
https://github.com/rakshasa/rtorrent/issues/501
https://github.com/rakshasa/rtorrent/issues/457

Host OS: Debian Jessie

I don't know if there is a way in Alpine to base the crypto library on OpenSSL. I tried replacing libressl-dev with openssl-dev and got package conflicts.

**Comment by dewey** [comment]
Are you on the latest version? This was fixed in https://github.com/linuxserver/docker-rutorrent/issues/33 afaik

**Comment by ChromoX** [comment]
I am. I checked out HEAD and did a docker built on my server.

I'm not 100% on what the error actually is. I just found ruTorrent RPC timeouts and noticed that rTorrent was pegged to 100% cpu usage. I looked in the logs directory at the rtorrent.log but found nothing of use in there.
