### ISSUE TITLE
Missing /var/log/{nginx,php7} on startup, won't run

### ISSUE THREAD

**Issue by bglopez** [linuxserver/docker-rutorrent#45]
On startup using Portainer the container will not complete starting and thus be inaccessible.

`nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (2: No such file or directory)
[21-Mar-2017 06:04:01] ERROR: failed to open error_log (/var/log/php7/error.log): No such file or directory (2)
[21-Mar-2017 06:04:01] ERROR: failed to post process the configuration
[21-Mar-2017 06:04:01] ERROR: FPM initialization failed
2017/03/21 06:04:01 [emerg] 246#246: open() "/var/lib/nginx/logs/access.log" failed (2: No such file or directory)
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (2: No such file or directory)
[21-Mar-2017 06:04:02] ERROR: failed to open error_log (/var/log/php7/error.log): No such file or directory (2)
[21-Mar-2017 06:04:02] ERROR: failed to post process the configuration
[21-Mar-2017 06:04:02] ERROR: FPM initialization failed`

This can be resolved by mounting /var/log in the container to anywhere (I let Docker decide) which leads to a successful start and run.

This occurs on quite a few other containers when using Portainer and the resolution is the same for those as well.

**Comment by sparklyballs** [comment]
looks like you've altered something or have a crossed config path because the ruttorrent container doesn't log there, it logs in a folder off the /config mount.

![screen shot 2017-03-21 at 08 10 28](https://cloud.githubusercontent.com/assets/4343808/24137972/216d8956-0e0e-11e7-8367-765b6539174a.png)

**Comment by bglopez** [comment]
It could be an OS thing. Portainer is running on CentOS 7. Those are the defaults that it fails with.

<img width="1411" alt="screen shot 2017-03-21 at 01 33 55" src="https://cloud.githubusercontent.com/assets/16629053/24138703/85417f7e-0dd6-11e7-93c6-9e82361e4c22.png">

**Comment by sparklyballs** [comment]
something isn't right your end because as i said earlier the ruttorrent container doesn't log there.

https://github.com/linuxserver/docker-rutorrent/blob/master/root/defaults/nginx.conf#L46

**Comment by j0nnymoe** [comment]
Quick question, did you install docker on centos via default yum repo's or from the official docker repo?

**Comment by bglopez** [comment]
Docker is via repo, yes. It *is* possible the issue on my end, I'm just pointing it out and giving my workaround for it in case someone else has this issue. I can provide any logs you'd like or any other pieces of troubleshooting info, just let me know.

**Comment by j0nnymoe** [comment]
I am assuming this is no longer an issue. If it is - please re-open this and we can look into it further.
Thanks.
