### ISSUE TITLE
Permission Denied when trying to upload .torrent file

### ISSUE THREAD

**Issue by fahadysf** [linuxserver/docker-rutorrent#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu 14.04.2

My run command is:
docker create --name=rutorrent \
-v /etc/rutorrent:/config \
-v /var/www/files:/downloads \
-e PGID=1001 -e PUID=1001 \
-e TZ=Asia/Riyadh \
-p 2080:80 -p 5000:5000 \
-p 51413:51413 -p 6881:6881/udp \
linuxserver/rutorrent

$ id rtuser
uid=1001(rtuser) gid=1001(rtuser) groups=1001(rtuser)

GID/UID

User uid:    1001
User gid:    1001

2017/04/05 00:13:11 [crit] 251#251: *1 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: 2.91.240.11, server: _, request: "POST /php/addtorrent.php HTTP/1.1", host: "v2.fahad.ga:2080", referrer: "http://v2.fahad.ga:2080/"

No symlinks used

**Comment by j0nnymoe** [comment]
I assume the rtuser has access to the `-v /etc/rutorrent:/config 
-v /var/www/files:/downloads` locations?

**Comment by fahadysf** [comment]
Yes. /etc/rutorrent and /var/www/files are both owned by 'rtuser'. I've even put 766 permissions on both just to be sure but doesn't make any difference.

/etc/rutorrent/logs/nginx/rutorrent.error.log still shows:

2017/04/05 11:05:11 [crit] 261#261: *1 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: 2.91.240.11, server: _, request: "POST /php/addtorrent.php HTTP/1.1", host: "v2.fahad.ga:2080", referrer: "http://v2.fahad.ga:2080/"

**Comment by markpash** [comment]
The user (abc in this case) doesn't have permissions on `/var/lib/nginx/tmp`. `chown -R abc /var/lib/nginx` (inside the container) seems to fix it though there is likely a better way.

**Comment by aptalca** [comment]
That's weird, because the container does chown that folder during start: https://github.com/linuxserver/docker-rutorrent/blob/master/root/etc/cont-init.d/20-config#L55

**Comment by markpash** [comment]
The previous fix seems to be temporary, though this does look like the same issue documented here [https://github.com/dockerfile/nginx/issues/4](https://github.com/dockerfile/nginx/issues/4)

**Comment by aptalca** [comment]
I cannot reproduce this issue. I grab a torrent file from http://torrent.ubuntu.com:6969/ ;-) and it uploads from file just fine

**Comment by markpash** [comment]
I didn't receive the error by uploading torrent files to rutorrent, I get errors by sonarr using the xmlrpc interface, same errors show up in the logs and it happens very often. I'll add the directive to nginx.conf to use /tmp and see if it solves my issues.

**Comment by markpash** [comment]
I added the directive `client_body_temp_path /tmp 1 2;` to `nginx.conf` and no problems since.

**Comment by dearsikandarkhan** [comment]
Thank you @MarkPash saved lot of my time.

**Comment by artik** [comment]
@MarkPash Mark,  after 2 weeks for searching the issue, you gave us the right answer. Just edit `/config/nginx/nginx.conf` to add `client_body_temp_path /tmp 1 2;` in the http bloc (below the line `client_max_body_size 0;` for example). But I still have these errors:   
                                                                     
```
2020/05/02 19:02:14 [crit] 347#347: *7494 open() "/var/tmp/nginx/fastcgi/5/00/0000000005" failed (13: Permission denied) whil
e reading upstream, client: 172.17.0.1, server: _, request: "POST /plugins/httprpc/action.php HTTP/1.1", upstream: "fastcgi:/
/127.0.0.1:9000", host: "192.168.0.2:50000", referrer: "http://192.168.0.2:50000/"                                           
2020/05/02 19:02:24 [crit] 349#349: *7561 open() "/var/tmp/nginx/fastcgi/6/00/0000000006" failed (13: Permission denied) whil
e reading upstream, client: 172.17.0.1, server: _, request: "POST /plugins/httprpc/action.php HTTP/1.1", upstream: "fastcgi:/
/127.0.0.1:9000", host: "192.168.0.2:50000", referrer: "http://192.168.0.2:50000/"                                           
2020/05/02 19:02:25 [crit] 348#348: *7662 open() "/var/tmp/nginx/fastcgi/7/00/0000000007" failed (13: Permission denied) whil
e reading upstream, client: 172.17.0.1, server: _, request: "POST /plugins/httprpc/action.php HTTP/1.1", upstream: "fastcgi:/
/127.0.0.1:9000", host: "192.168.0.2:50000", referrer: "http://192.168.0.2:50000/"   
```

The full fix is to add in `nginx.conf`:

```
        client_body_temp_path /tmp/client_body 1 2;                                                                          
        fastcgi_temp_path /tmp/fastcgi 1 2;                                                                                  
        proxy_temp_path /tmp/proxy;                                                                                          
        uwsgi_temp_path /tmp/uwsgi;                                                                                          
        scgi_temp_path /tmp/scgi; 
```

**Comment by doctorpangloss** [comment]
I would reopen this issue, the fix above worked for me. To clarify, you should add the above to the `http {` section of your `/config/nginx/nginx.conf` file.
