### ISSUE TITLE
URLBASE for rutorrent

### ISSUE THREAD

**Issue by gautenk** [linuxserver/docker-rutorrent#51]
Hi,
Is it possible to add an URLBASE function to this container? It would make it easier to put it behind a reverse proxy.

Thanks!

**Comment by sparklyballs** [comment]
the nginx conf is exposed at `/config/nginx/nginx.conf` 

you can edit that to allow for a `/rutorrent` url base for example.

**Comment by gautenk** [comment]
That was not the question. Is it possible to add an easier way to do it? Like in the docker create command? This is a feature request.

**Comment by sparklyballs** [comment]
but it is nonetheless the answer.
