### ISSUE TITLE
rtorrent process not gracefully terminated

### ISSUE THREAD

**Issue by deed02392** [linuxserver/docker-rutorrent#58]
When running docker stop on this container, the rtorrent lock file is not deleted. 

The fact this lock file is left behind indicates rtorrent isn't gracefully shutting down. This can cause issues with state data in rtorrent.

**Comment by sparklyballs** [comment]
non-issue arising from unsupported use of /config mounted on nfs shares

**Comment by deed02392** [comment]
Wrong again @sparklyballs . I already tested this on a local fs mount for /config and rtorrent.lock is not removed. Otherwise I suspect you wouldn't have included the 'rm' command as part of the cont-init script in the first place.
