### ISSUE TITLE
Why is this not an automated build on the Docker hub?

### ISSUE THREAD

**Issue by lanrat** [linuxserver/docker-rutorrent#62]
Most of the linuxserver.io builds are automated builds, which is a nice guarantee that when the repository is updated the image is as well. That does not appear to be the case with this one. Is there any particular reason why? Can it be moved to an automated build? 

https://hub.docker.com/r/linuxserver/rutorrent/

Thanks.

**Comment by sparklyballs** [comment]
most of the linuxserver builds are NOT automated builds

we use jenkins to monitor changes to the git repo and build when a PR is approved and merged
