### ISSUE TITLE
on first start - /tmp/screens issue

### ISSUE THREAD

**Issue by Symbiot78** [linuxserver/docker-rutorrent#64]
Hi

When I start the docker the logs shows:

`fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Directory '/tmp/screens' must have mode 755.`

I can then send a command to chmod 755 /tmp and rm -rf /tmp/screens
Commit the container and redo all the config and start the docker. And everything works.
Then if I do a restart it will again ask for 755 perms.

This is on the newest container pulled 3 days ago.

**Comment by thelamer** [comment]
Cannot duplicate on current images. 

/tmp is 777 and /tmp/screens is 755 on first spinup. 

If you are messing about inside the container is it possible that you have not completely removed and replaced the container on update? 

As this folder is embedded in the container storage layer on replacing the container it will be exactly as it is on my machine or anyone elses.
