### ISSUE TITLE
Synology/Docker/rTorrent - Port is Closed

### ISSUE THREAD

**Issue by CaptainSolo2** [linuxserver/docker-rutorrent#68]
I am posting this here simply to help other people who are likely having the same issue. I also posted in the forums, here... so that when people search for this problem they can find the solution:
https://forum.linuxserver.io/thread-545.html

To summarize, I used this guide to install the Docker container on my Synology NAS. (DS-1517+)
https://drfrankenstein.co.uk/2016/11/22/setting-up-rutorrent-in-docker-on-a-synology-nas/

Everything worked fine (mostly)... I can download files and I have verified that they are seeding by logging into my trackers and seeing them in my seedlist. However, at the bottom of the rTorrent client there is a red icon that says "51413: Port is Closed". My guess is that this is preventing anyone from actually connecting with the files.

This container is awesome and great for people like me who dont know Linux... but I am not really sure how to fix this. I tried a port forward on my router, but that didnt help. My guess is that I need to do something on the NAS to get it to communicate with Docker maybe, but I'm not sure. 

Any help would be appreciated!

**Comment by tobbenb** [comment]
You most likely forgot to add a port mapping for 51413 when you created the container.
Don't know how you can add it on a synology.

**Comment by CaptainSolo2** [comment]
Thanks for responding! I followed the steps in the guide verbatim - as did several others who had the same problem. I suspect no one else followed up on this because they didn't realize that the Listening port (the 51413) being closed was actually a problem since by all outward appearances, everything seems to be working fine. (ie, you can download files, and it even looks like you are actively seeding when really you are passively seeding, etc)

Setting up the ports on the NAS is pretty straight-forward - there is a GUI panel for it, so you dont have to do it from the command line. I added a new port setting, where local port was set to "Auto" and Container port was set to "51413". Once that is saved, the container selects a specific local port (we'll call it "33333"), so the mapping on the Container side is complete, I think. I can see that local port 33333 is mapped to Container port 51413.

So in theory, the final step would be to go to my router and set up a port forward by selecting the NAS IP and entering the port number selected by the container above (the 33333).

But.... rTorrent is still telling me the port is closed. (I tried adding a port forward for 51413 too, but got the same result.)

I noticed in the info page that there is a reference to port 6881, which the Dr Frankenstein guide (which is now a year old) doesnt mention that port at all. What is that port used for and should there be a port setting for that too?

I'm so close... and yet so far! Im wondering if there are some additional Container ports that need to be open or something.

**Comment by tobbenb** [comment]
If you connect to the container with a client that expects to use port 51413, then you need to use that port on the host side also.

**Comment by CaptainSolo2** [comment]
Holy crap. Dude. I just went back to the Linux container and changed the port from 33333 to 51413, then came back to rTorrent and re-checked the port status... and BOOM. Green check mark.

You sir... have made another man very happy. Like, I'm gonna hug you... give you a single slap on the back... then slowly back away and say "Thanks Bro... here is a beer."

Now I just need to figure out how to get the Container to communicate from behind a VPN and Im golden. 

_________________________________________________________________
For anyone coming across this later, I wrote up instructions on how to fix this, located here:
[https://forum.synology.com/enu/viewtopic.php?f=190&t=137164](https://forum.synology.com/enu/viewtopic.php?f=190&t=137164)

**Comment by CaptainSolo2** [comment]
Im still digging around the web for this, but maybe you can point me in a direction. How would someone connect this container to a VPN provider like PIA?

I can set up a VPN profile on my NAS, but when I do that the Listen Port loses connectivity again. What's interesting is that the rest of the Container appears to still be functioning correctly - I can DL files and they are appearing in my seed lists. The only issue seems to be the Listen Port.

Im guessing there is some additional step that is needed to get the Listen Port to remain open when alongside the IP in the VPN Profile.

**Comment by tobbenb** [comment]
Good that you got it going.
I'm not sure how to get this going through a VPN though.

**Comment by CaptainSolo2** [comment]
That's really the last frontier, I think... bc I think most people using this are going to want to mask their IP address.

I'm experimenting right now - Its interesting to me that the Container maintains connectivity through the VPN when the VPN profile is enabled. (Ive verified that with IPMagnet, and my real IP was definitely masked.) 

The only problem seems to be that the Listen Port closes when the VPN profile is turned on.

**Comment by aptalca** [comment]
You have to port forward on VPNs for incoming connections. Some VPNs only allow a single or a few ports to be forwarded, which is an issue for rtorrent, because it listens on a range of IPs by default. You would have to set rtorrent to a specific listening port and forward that on the VPN

**Comment by CaptainSolo2** [comment]
Hmmmm. Ok, that makes sense. The good news is that the guide for this particular setup relies on only one port for the listen port (which obviously someone can change, but I didnt.)

It sounds like I need to experiment with port forwarding on the NAS itself. There are definitely some features on there that I think may help me resolve this. I'll post back once I know more. Thanks!

**Comment by schwyl** [comment]
I've been having this issue now for a few months.

Here's the code for the docker creation
https://pastebin.com/Q5eFULqg

Here's the port mapping on my router:
https://imgur.com/a/IHP5k

I can access the webui for rutorrent using the 8881 ports with no issue

**Comment by Artiume** [comment]
> I've been having this issue now for a few months.
> 
> Here's the code for the docker creation
> https://pastebin.com/Q5eFULqg
> 
> Here's the port mapping on my router:
> https://imgur.com/a/IHP5k
> 
> I can access the webui for rutorrent using the 8881 ports with no issue

Don't change the port for the port that you intend to port forward. 
60001:51413
Change this back to 51413:51413 and port forward that port on your router.
Another option is to use a vpn-rutorrent combination and you wont have to worry about port forwarding, 
https://hub.docker.com/r/binhex/arch-rtorrentvpn/ this is what I use.
https://github.com/Artiume/docker/blob/master/vpn-rutorrent.yml Here is my working yml.
