### ISSUE TITLE
RAM Consumption - Container having trouble with cached vs available RAM?

### ISSUE THREAD

**Issue by CaptainSolo2** [linuxserver/docker-rutorrent#70]
I'm running into a memory issue on a device that has plenty of RAM (16 GB): There seems to be a disconnect between the amount of RAM the container think it is using vs what is actually being used. It's possible there is a memory leak, but I think the issue may be that the container isn't handling cached RAM correctly, or maybe it isn't differentiating between cached RAM and available RAM?

In the screencap below, you can see where the container says it is using a large amount of RAM, but the system's Resource Monitor shows something else. Once the container hits around 13.5 GB, the color will change from green to orange or red, then the system locks up and I have to restart the container.

Not sure what the fix is here, but I thought you would want to know. 
[]https://i.imgur.com/TIHfvU7.png

**Comment by CaptainSolo2** [comment]
Edit #1. As an addendum, I think there is some correlation between this issue and performing Force Re-checks within rTorrent. (It's expected that this would require RAM, but maybe the Docker container is "holding on to it" for some reason?)

Edit #2. I think I found the actual problem. When you are cross-seeding files between trackers, it's very common to discover you are missing the info file, or images, or a sample, etc. When that happens, you typically just leave the file open in your client (in Download mode) so that when someone comes along with the entire set of files, you pick up the missing pieces and are instantly cross-seeding. I had 5 such files open in the client... and when I removed all five of them, the part of the memory issue went away.... .

...but there still seems to be an issue after performing re-checks. (ie, After you perform multiple re-checks, the RAM consumption increases until the container locks up.)

Not sure why that would be a problem for the container here... but apparently it is. So there ya go.... something to maybe look at :-)

**Comment by thelamer** [comment]
I run this container in multiple environments and do not have any issues with ram consumption. 

Also from the sounds of it either do you, it is just how Synology displays it in their web interface. 

I would recommend reaching out to them about this issue: 

https://account.synology.com/support/support_form.php
