### ISSUE TITLE
base image relies on x64 binary

### ISSUE THREAD

**Issue by leonixyz** [linuxserver/docker-rutorrent#72]
### Host OS
[Arch Linux ARM](https://archlinuxarm.org/)

### run/create command
```
$ sudo docker run --name=rutorrent \
-v /media/fatboy/downloads:/downloads \
-e PGID=1001 -e PUID=1001 \
-e TZ=Europe/Rome \
-p 80:80 -p 5000:5000 \
-p 51413:51413 -p 6881:6881/udp \
linuxserver/rutorrent
```

### $ docker log rutorrent
```
standard_init_linux.go:195: exec user process caused "exec format error"
```

### Mention if you're using symlinks on any of the volume mounts
No.

### What you think your suggestion brings to the project, or fixes with the project
*linuxserver/rutorrent* is based on parent image [lsiobase/alpine:3.7](https://github.com/linuxserver/docker-baseimage-alpine) which seem to `ADD rootfs.tar.xz /` on line 2 of its [Dockerfile](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile).  
I think that tarball contains some pre-compiled Go binary, which cannot be executed on an ARM device.

#### If it's a fix, would it be better suited as a Pull request to the repo ?
No, because I cannot see the content of file `rootfs.tar.xz`.

**Comment by tobbenb** [comment]
Might be better to use the arm version. https://github.com/linuxserver/docker-rutorrent-armhf
