### ISSUE TITLE
Bad response from server: Link to XMLRPC failed. May be, rTorrent is down?

### ISSUE THREAD

**Issue by mkz71** [linuxserver/docker-rutorrent#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

I got this error every 5 to 10 minutes.

Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?

or 

Bad response from server: (500 [error,gettotal]) Link to XMLRPC failed. May be, rTorrent is down?

I run my container from latest build, 125, on Coreos version 1576.4.0.

Thanks,

**Comment by homerr** [comment]
I'll close this off as it appears stale, and opened under a pre-pipeline built version of rutorrent which has had a bit of a rewrite. If the issue persists, re-open and we can look into it.
