### ISSUE TITLE
Password ?

### ISSUE THREAD

**Issue by 3th3r** [linuxserver/docker-rutorrent#74]
How can we had a password ?
I didn't find the .rtorrent folder to put a .htpasswd.

And I'm sure it will work with an othe nginx proxy.

**Comment by stevesbrain** [comment]
I just chucked it behind a reverse proxy - was the simplest way for me given I was already using it. However, you can just modify the nginx.conf file to set up the htpasswd there.

**Comment by sparklyballs** [comment]
you can edit the nginx conf to set up auth

**Comment by lvitti** [comment]
Could you explain how to modify the nginx configuration file to accept passwords?

**Comment by alex-phillips** [comment]
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by ghiki** [comment]
Anyone can help with this?

I followed these doc, but wen I try to login, I see this in registry and can't click in any button;
Bad response from server: (0 [error,getplugins]) 

My actual "nginx.conf":
```
http {

	##
	# Basic Settings
	##
	auth_basic "ruTorrent admin.";
    auth_basic_user_file /config/nginx/.htpasswd;
```

And obviously, there's a .htpasswd in /config/nginx folder
