### ISSUE TITLE
Not Connectable

### ISSUE THREAD

**Issue by schwyl** [linuxserver/docker-rutorrent#75]
I've been having this issue now for a few months.

Here's the code for the docker creation
https://pastebin.com/Q5eFULqg

Here's the port mapping on my router:
https://imgur.com/a/IHP5k

I can access the webui for rutorrent using the 8881 ports with no issue

**Comment by j0nnymoe** [comment]
Have you tried this with the ports suggested in the readme?
`docker create --name=rutorrent \
-v <path to data>:/config \
-v <path to downloads>:/downloads \
-e PGID=<gid> -e PUID=<uid> \
-e TZ=<timezone> \
-p 80:80 -p 5000:5000 \
-p 51413:51413 -p 6881:6881/udp \
linuxserver/rutorrent`

**Comment by schwyl** [comment]
Hi there, Sorry took so long.

Yeah I built a new docker using all ports. all ports are forwarded but I still remain not connectable

**Comment by thelamer** [comment]
When you say not connectable are you referring to the exclamation mark about 51413 not being open on the bottom of the web interface ?? 

If this is the case then you need to forward 51413. 

Side note exposing this web interface to the internet is a bad idea.

**Comment by homerr** [comment]
Stale, closed
