### ISSUE TITLE
rutorrent filemanager plugin

### ISSUE THREAD

**Issue by Anon0511** [linuxserver/docker-rutorrent#82]
Hey,

I would kindly ask to add the filemanager plugin since it allows the user to quickly check files, download those and unzip them if needed. Basically useful for everyone with a proper SSH Setup who is not carrying all day his SSH Key on Mobile and Work Devices (beside firewall restrictions and such).

My start command:
docker run -d --restart always --name=rutorrent \
-v /home/user:/config \
-v /home/user/downloads:/downloads \
-v /home/user/rutorrent/plugins:/usr/share/webapps/rutorrent/plugins \
-e PGID=1000 -e PUID=1000 \
-e TZ=Europe/Berlin \
-p 5000:5000 \
-p 51413:51413 \
--network=isolated \
linuxserver/rutorrent

In this case I can add plugins into the desired folder while in the initial process no plugin at all gets installed (they are installed if you don't mount the plugin folder).

I added the filemanager:
svn co -q https://github.com/nelu/rutorrent-thirdparty-plugins/trunk/filemanager

And needed to hardcode the additional programs in the filemanager/conf.php:
$pathToExternals['unrar'] = '/usr/bin/unrar';
$pathToExternals['zip'] = '/usr/bin/zip';
$pathToExternals['unzip'] = '/usr/bin/unzip';
$pathToExternals['tar'] = '/usr/bin/tar';
$pathToExternals['bzip2'] = '/usr/bin/bzip2';
$pathToExternals['rar'] = '/usr/bin/rar';  #Not installed

#Not too sure if rar->unrar is correct tho but at least there is no rar in 'which rar'.

And last we need to get rid of the error "Failed to get directory contents : /" with:
apk add --no-cache findutils

Another great addon onto this would be fileshare. I have not tested it yet, neither am I able to test if the filemanager is correctly working but at least there are no errors anymore. Fileshare makes it possible to share any of the files located in the filemanager for a given duration, a password you can specify and generates an individual link to give it to friends. It will most likely need a pretty special nginx conf.

**Comment by Anon0511** [comment]
PPS: Filemanager extracting doesn't work which is necessary for Plex to get the actual media file.
FATAL ERROR: Destination not permitted

1. The following fix should be used to get rid of the errors in /log/nginx/rutorrent.error.log:
https://github.com/nelu/rutorrent-thirdparty-plugins/pull/33/files

2. Set the rutorrent $topDirectory:
/rutorrent/settings/config.php
 $topDirectory = '/downloads/';                   // Upper available directory. Absolute path with trail slash.

**Comment by Anon0511** [comment]
As of now I found out that automatic extract from the options menu work, but not manually.

**Comment by alex-phillips** [comment]
New PR will allow custom plugins to be added to your instance: https://github.com/linuxserver/docker-rutorrent/pull/101
