### ISSUE TITLE
Torrent state not saving

### ISSUE THREAD

**Issue by anstosa** [linuxserver/docker-rutorrent#86]
The container, UI and daemon boot up great and I understand that I cannot change rtorrent settings in a persistent way via the UI. However the torrent state is also not persisting. The torrents are still there, but if they're paused when I turn off the container, they start again when I restart it and if I've changed the download locations of specific torrents they revert to the default download location. Any ideas?

**Comment by anstosa** [comment]
Nevermind. Learned that rtorrent persists data to disk every 20mins or at clean shutdown. Wait longer or don't kill your container

**Comment by themightykitten** [comment]
I also have this problem. rTorrent is supposed to save the session state as often as you tell it to in the rtorrent.rc file. But it looks more like the container exists badly, and this is clearly not the first time the issue has been reported here: 
see #77 #58 #61 etc
