### ISSUE TITLE
Country column does not appear on the ruTorrent peers tab.

### ISSUE THREAD

**Issue by ACiDxCHRiST** [linuxserver/docker-rutorrent#89]
Something appears to be messed up in the internal config for the geoip plugin of ruTorrent. The plugin shows that it is enabled and I don't see any issues in the logs but the Country column on the peers tab which displays a peers country flag and name is not present.

**Comment by lol2025** [comment]
i have the same issue, even though i download the GeoIP date and move it to /usr/share/GeoIP/

**Comment by nomandera** [comment]
I see ISO country code here but not the flag. Is a flag icon expected?

**Comment by j0nnymoe** [comment]
Closing this as there are other issues open regarding the same thing: https://github.com/linuxserver/docker-rutorrent/issues/103
