### ISSUE TITLE
Container keeps pausing

### ISSUE THREAD

**Issue by itapai** [linuxserver/docker-rutorrent#91]
As the title says, the container keeps pausing on creation and after I unpause it.
The OS is a fresh ubuntu bionic install.
Initially I thought it was a port/firewall problem, so I disabled ufw, but it didn't help. 
Same thing happens with the linuxserver/transmission image. Radarr and sonarr working fine. 
Any ideas?

I created the container with the following ( as per documentation ): 

```
docker create --name=rutorrent \
-v /opt/rtorrent:/config \
-v /data/downloads:/downloads \
-e PGID=1001 -e PUID=1001 \
-e TZ=Europe/London \
-p 80:80 -p 5000:5000 \
-p 51413:51413 -p 6881:6881/udp \
linuxserver/rutorrent
```

When I start the container, I can access it via url for 1 minute then it pauses
```
$ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                                                                                          NAMES
bd44a5ad8343        linuxserver/rutorrent   "/init"             2 minutes ago       Up About a minute (Paused)   0.0.0.0:80->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:51413->51413/tcp, 0.0.0.0:6881->6881/udp   rutorrent
```
```
$ docker logs rutorrent
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
'access-swap.sh' -> '/config/rutorrent/settings/access-swap.sh'
'access.ini' -> '/config/rutorrent/settings/access.ini'
'access_no' -> '/config/rutorrent/settings/access_no'
'access_yes' -> '/config/rutorrent/settings/access_yes'
'config.php' -> '/config/rutorrent/settings/config.php'
'plugins.ini' -> '/config/rutorrent/settings/plugins.ini'
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by homerr** [comment]
It doesn't look paused? Once it gets to done. everything is running and you should be able to access the webui on port 80

**Comment by aptalca** [comment]
I don't believe containers pause due to internal elements. Something else on your system must be issuing a pause request to docker service for either that container or all containers

**Comment by itapai** [comment]
Do you know what the cause might be? 
I tried googling the issue, but no success.

**Comment by homerr** [comment]
Did you ever figure this out? I must admit you're the only person I've ever found with paused containers.

**Comment by itapai** [comment]
Yes, I figured it out in the end. 
Someone planted a mining script that would stop all running containers and mine.

Forgot to close this issue, since it's clearly not a docker related issue.

**Comment by homerr** [comment]
Wow! Glad you caught that one. Let us know if you need any help with the container in the future 👍
