### ISSUE TITLE
Schedule lines are not taken into account

### ISSUE THREAD

**Issue by the-lazy-fox** [linuxserver/docker-rutorrent#93]
Hello,
I have the following watch directories but it doesn't work correctly in this docker image but it was in my previous install outside Docker.
```
schedule = watch_software,5,5,"load_start=/downloads/__source/software/*.torrent,d.directory.set=/downloads/software,d.set_custom1=software"
schedule = watch_tmpmovies,5,5,"load_start=/downloads/__source/tmp-movies/*.torrent,d.directory.set=/downloads/_tmp/movies,d.set_custom1=tmp-movies"
```
Any hints?
Thanks!

**Comment by bachmma1** [comment]
Hi,
May it have to do with the newest rTorrent version (0.9.7) in this docker image.
I had some issues with my web-gui regarding the (deprecated) command-changes.

1) be sure, that the „schedule =„ is unique for watching
2) ex-change „load_start=„ with „load.start_verbose“.

Example from the config-template from github-wiki:

Watch directories (add more as you like, but use unique schedule names)

* Add torrent
schedule2 = watch_load, 11, 10, ((load.verbose, (cat, (cfg.watch), "load/*.torrent")))
* Add & download straight away
schedule2 = watch_start, 10, 10, ((load.start_verbose, (cat, (cfg.watch), "start/*.torrent")))

Hope this helps ;)

Best regards

**Comment by the-lazy-fox** [comment]
Thanks!
By unique you mean it needs to be schedule, schedule2, schedule3, etc?
For your examples:
- what does the number means?
- where to but the label I have it to have?
- where to put the download path?

**Comment by bachmma1** [comment]
I also missunderstood it first...
the command itself is "schedule2". So this always have to be "schedule2".

The description of the command is as follows [(ReadTheDocs.io --> schedule2](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-schedule2):
`schedule2 = ‹name›, ‹start›, ‹interval›, ((‹command›[, ‹args›…])) ≫ 0`
`schedule2 = ‹name›, ‹start›, ‹interval›, "‹command›=[‹args›…][ ; ‹command›=…]" ≫ 0`


- schedule2 --> is the command of the scheduler itself
- \<name\> --> is the name of the task. <b>This have to be unique</b>
- \<start\> --> is the delay for the scheduled task after rtorrent starts up in seconds.
- \<interval\> --> is the interval of the scheduled task in seconds. So run task every X seconds
- \<command\> --> is (are) the rtorrent-command(s) which should be run

Hint: start and interval may optionally use a time format like [dd:]hh:mm:ss

Taken your example:
<pre>
schedule = watch_software,5,5,"load_start=/downloads/__source/software/*.torrent,d.directory.set=/downloads/software,d.set_custom1=software"
</pre>

I guess this should look like this in the "new" format:

<pre>
schedule2 = watch_software,5,5,"<b>load.start</b>=/downloads/__source/software/*.torrent<b>;</b>d.directory.set=/downloads/software<b>;d.custom1.set</b>=software"
</pre>

Answers to your questions:
- what does the number means?
--> the numbers stand for start and interval
- where to but the label I have it to have?
--> I don't know which label you are refering to. From my view there are two. 
one is the \<name\> which labels the task. 
the other is the d.custom1.set which tags the torrent itself with a custom "xml-rpc-attribute".
- where to put the download path?
--> d.directory.set is the path where the torrent will be downloaded to.

Cheers

**Comment by the-lazy-fox** [comment]
If we could give a medal for the best support and explanation, it would be yours!
Thanks man!
I will give it a try. 

In the meantime, I have activated the AutoWatch part of autotools and it seems to do the job also.

**Comment by bachmma1** [comment]
Wow, thank you very much!
It‘s always a pleasure to help as I know from myself how cool it is when it works at the end how it should resp. how you planed it ;)

Alright, I guess thats the graphical way of activating watchfolders xD

If you run into any problems, just ask ;)

**Comment by the-lazy-fox** [comment]
Hey @bachmma1,
Do you know how to increase the frequency of "AutoWatch" feature when not using schedule?
Thanks
