### ISSUE TITLE
Add Support For Mobile View

### ISSUE THREAD

**Issue by viveksupe** [linuxserver/docker-rutorrent#99]
Add feature to support 3rd party plugin like [ruTorrentmobile](https://github.com/Novik/ruTorrent/wiki/Plugins) for mobile navigation/web view.

Add plugin contents to `./app/rutorrent/plugins/mobile`

Content: https://github.com/JimmyLaurent/ru-mobile

**Comment by viveksupe** [comment]
Closing it. Seems the author currently does not maintain the project may not be the best thing to add in.

https://github.com/JimmyLaurent/ru-mobile/issues/1
> Sorry I don't really have the time to maintain this project.

**Comment by alex-phillips** [comment]
@viveksupe new PR adds support for adding plugins: https://github.com/linuxserver/docker-rutorrent/pull/101
